### ISSUE TITLE
Uncaught TypeError: Cannot read property 'url' of undefined after episode 35

### ISSUE THREAD

**Issue by rakvium** [DmitrS/RSS#2]
JS Error when trying to receive episode 34.

![screenshot from 2016-12-16 19-06-27](https://cloud.githubusercontent.com/assets/6672367/21271322/359b0ad8-c3c3-11e6-89a4-18c0f9265b8a.png)

**Comment by DmitrS** [comment]
@rakvium fixed c1a3f4312f4d2544087ac0cc498b3e9c9c1a8e47
